server:
  port: 8090
  netty:
    connection-timeout: 10000s

spring:
  application:
    name: ai-chat-gateway
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:chat_history.db
    username:
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rag:
  enabled: true
  top-k: 3
  max-chunks-scan: 2000
